### ISSUE TITLE
examples with screenshoot

### ISSUE THREAD

**Issue by b4zz4** [admesh/admesh#13]
The captures of screen and the code to illustrate that it does the source code

-- 

las capturas de pantalla y el codigo para ilustrar que hace el codigo fuente

**Comment by hroncok** [comment]
I'm afraid I don't understand the meaning of this issue.

**Comment by b4zz4** [comment]
Dont panic!

I believe that to understand better the program serious better some examples have with the captures of screen and the files stl that are used in the examples.

thanks

Miro Hrončok:
> I'm afraid I don't understand the meaning of this issue.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/admesh/admesh/issues/13#issuecomment-134119840
>

-- 
http://ba.zza.pl
gpg: http://ba.zza.pl/bazza.asc

**Comment by hroncok** [comment]
Documentation, including this kind of stuff, is work in progress in docs
branch and available on https://admesh.rtfd.org

**Comment by b4zz4** [comment]
:smile:
