### ISSUE TITLE
Build release with last commit

### ISSUE THREAD

**Issue by oriolbcn** [admesh/admesh#16]
Could you please build a new release with the last commit? I would do it myself by I don't think this can be done by contributors.

Thanks!

**Comment by hroncok** [comment]
I will not release it as a new version yet, as it breaks the ABI so I will do more changes later to not break ABI so often, including #10. Would you like a source tarball or Windows build or?

**Comment by oriolbcn** [comment]
Thanks for the quick response! I understand, don't worry I'll create a new release on my fork for now so that I have it accessible, will check when you create the new release with the added changes.
