### ISSUE TITLE
Wrong NULL check in Allocate memory for the neighbors list

### ISSUE THREAD

**Issue by zgres** [admesh/admesh#18]
stlinit.c line 157
155:  /* Allocate memory for the neighbors list */
156:  stl->neighbors_start = (stl_neighbors*) calloc(stl->stats.number_of_facets, sizeof(stl_neighbors));
157:  if(stl->facet_start == NULL) perror("stl_initialize");

Need to check (stl->neighbors_start == NULL)!

**Comment by hroncok** [comment]
Seems right. Can you send a pull request?
