### ISSUE TITLE
Windows: the converting from ascii stl to binary is incorrect

### ISSUE THREAD

**Issue by graywolf2** [admesh/admesh#23]
In Windows I use the following command for converting:
admesh.exe -b output.stl input.stl
After converting the output.stl file is incorrect. I can not view the output.stl in openscad or fstl.

admesh version is 0.98.2.
The converting works normally in Fedora Linux 24 64bit.

I attached some stl files for check.
[check_stl_files.zip](https://github.com/admesh/admesh/files/475730/check_stl_files.zip)
The r1.stl is the original input stl file.
The r1_b.stl is the correct binary output stl file which i generated in Fedora Linux.
The r2_b.stl is the incorrect binary output stl file which i generated in Windows 7 32bit.

The 64bit admesh in Windows 8 64bit also generates incorrect stl output file.

This is the admesh output from Windows 7 32bit:
ADMesh version 0.98.2, Copyright (C) 1995, 1996 Anthony D. Martin
ADMesh comes with NO WARRANTY.  This is free software, and you are welcome to
redistribute it under certain conditions.  See the file COPYING for details.
Opening r1.stl
Checking exact...
All facets connected.  No nearby check necessary.
No unconnected need to be removed.
No holes need to be filled.
Checking normal directions...
Checking normal values...
Calculating volume...
Verifying neighbors...
Writing binary file r2_b.stl

================= Results produced by ADMesh version 0.98.2 ================
Input file         : r1.stl
File type          : ASCII STL file
Header             : solid OpenSCAD_Model
============== Size ==============
Min X = -14.048400, Max X =  13.838600
Min Y = -13.887000, Max Y =  17.313000
Min Z = -9.480440, Max Z =  21.405500
========= Facet Status ========== Original ============ Final ====
Number of facets                 :   690                 690
Facets with 1 disconnected edge  :     0                   0
Facets with 2 disconnected edges :     0                   0
Facets with 3 disconnected edges :     0                   0
Total disconnected facets        :     0                   0
=== Processing Statistics ===     ===== Other Statistics =====
Number of parts       :     2        Volume   :  11488.410156
Degenerate facets     :     0
Edges fixed           :     0
Facets removed        :     0
Facets added          :     0
Facets reversed       :     0
Backwards edges       :     0
Normals fixed         :     0

**Comment by hroncok** [comment]
Did you forget to explain the issue, or is this a mistake?

**Comment by hroncok** [comment]
Is the exe downloaded from here or do you compile it yourself?

**Comment by graywolf2** [comment]
I did not compile the exe.
I checked the exe from this github repository. Also i checked the exe
from mingw32-admesh and mingw64-admesh packages of Fedora Linux. The
result was the same.

But In Fedora the admesh from admesh package works normally.
