### ISSUE TITLE
post installation error - not sure if installed properly

### ISSUE THREAD

**Issue by chen112p** [admesh/admesh#30]
Hello, I followed the instruction:
./configure
make

then i used "sudo make install"
I guess " sudo make install " should work in the same way as " su -c 'make install' "

After that, when I call admesh, it tells me:

admesh: error while loading shared libraries: libadmesh.so.1: cannot open shared object file: No such file or directory

Thanks

JT

**Comment by hroncok** [comment]
You probably need to set PREFIX to your environment. Do I assume right you are using something like Ubuntu? The admesh library is installed in /usr/local/lib and your system is not configured to see it when executing admesh app. See https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

**Comment by chen112p** [comment]
Thanks a lot. It works!

Yes I am using ubuntu.
